# Site settings
title: Szkoła Partyzantów
email: szkolapartyzantow@gmail.com
description: Szkoła Partyzantów # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

permalink: pretty

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed