# Site settings
title: Szkoła Partyzantów
email: szkolapartyzantow@gmail.com
description: Szkoła Partyzantów # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
